In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression

# Pandas library is used for importing various file types e.g. csv, excel, json.
# also used for manipulation and cleaning dataframes.

# Numpy library has functions used for working with arrays and matrices
# faster, clearer and better quality code using Numpy

# Matplotlib is a 2D plotting library for visualising data in Python

# Seaborn is used for improving Matplotlib visualisations to make them more visually attractive.
# It builds on top of MatPlotLib and works with Pandas for data structures

# sklearn is a library used for machine learning and statistical modeling.
# it includes many tools for classification, regression, clustering and dimensionality reduction

In [2]:
data = pd.read_csv("1.02.+Multiple+linear+regression.csv")
data.head()

# importing and displaying data the csv file

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [3]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

## Multiple Linear Regression

In [4]:
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

# First, declare the dependant (SAT, Rand 1,2,3) and independant variables (GPA)

In [5]:
reg = LinearRegression()
reg.fit(x,y)

# storing and fitting the linear regression model to the data

LinearRegression()

In [6]:
reg.coef_ 

# in output below, the first number is coefficient of SAT and the second is the coef of Rand 123
# this is the constant that is multiplied by the variable

array([ 0.00165354, -0.00826982])

In [7]:
reg.intercept_

# the intercept is the point where the function crosses the y axis (the predicted value for y when x is 0)

0.29603261264909486

In [8]:
reg.score(x,y)

#.score() returns the R-Squared of a linear regression (simple or multiple)

# however, the Adjusted R-Squared is more appropriate for multiple linear regerssion
# as it adjusts for multiple variables

0.40668119528142843

### Formula for Adjusted R^2
$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$
###### n = 84 (number of observations) and p = 2 (the number of predictors)

##### R-Squared is the universal measure for evaluating how well linear regressions perform

In [9]:
x.shape

(84, 2)

### Calculating the R-Squared

In [10]:
r2 = reg.score(x,y)
# variable storing the R-Squared value

n = x.shape[0]
# the number of observations

p = x.shape[1]
# the number of predictors (2)

adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2
# plugging in the variables into the R-Squared formula

0.39203134825134023

#### We can conclude that the Adjusted R Squared (0.39) is significantly lower than R Squared (0.40)
#### Therefore one or more of the predictors has little to no explanatory power
#### To find out which predictor is the least important we use feature selection:

## Feature Selection

#### Feature selection improves speed and prevents issues related to having too many features

In [11]:
from sklearn.feature_selection import f_regression

# importing feature_selection module from sklearn library
# f_regression creates simple linear regressions of each feature (SAT, Rand 1,2,3) and the dependant variable (GPA)

In [12]:
f_regression(x,y)
# applying the f_regression to the features (x) and target (y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [13]:
# first array shows F-statistics for each of the regressions
# Second array shows the corresponding P-values

In [14]:
p_values = f_regression(x,y)[1]
p_values
# storing the p-values from the regression in the variable 'p_values'

array([7.19951844e-11, 6.76291372e-01])

In [15]:
p_values.round(3)
# as the output is written in scientific notation, the p_values will be rounded to 3 digits

array([0.   , 0.676])

In [16]:
# the first p_value (0.00) is of the SAT, the second p_value (0.676) is of the Rand 1,2,3
# p_values above 0.05 or 5% are not significant, whereas below 0.05 are significant
# Therefore we know SAT is a useful variable whereas Rand 123 is useless

### Summary Table with P-values

In [17]:
reg_summary = pd.DataFrame(data = x.columns.values, columns=['Features'])
reg_summary
# creating a table with the features

Features
0         SAT
1  Rand 1,2,3

In [18]:
reg_summary ['Coefficients'] = reg.coef_
reg_summary ['p-values'] = p_values.round(3)
# provides the table with the coefficient and p-values of the features

In [19]:
reg_summary

Features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676

P-values help us determine whether a variable is significant or not, however not how useful it is