In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression
# importing the relevant packages

In [2]:
data = pd.read_csv("1.02.+Multiple+linear+regression.csv")
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [3]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

## Creating the Multiple Linear Regression

In [4]:
# First, declare the dependant and independant variables
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

In [5]:
# Regression itself
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [6]:
# Coefficient
reg.coef_ # in output below the first number refers to SAT and the 2nd refers to the Rand 123

array([ 0.00165354, -0.00826982])

In [7]:
# Intercept
reg.intercept_

0.29603261264909486

In [8]:
# Calculating the R-Squared below

In [9]:
# reg.score(x,y) can be used for both simple and multiple linear regression
reg.score(x,y) 
# the score below is for the R-Squared regression, NOT the Adjusted R-Squared
# (Adjusted R is more appropriate for multiple regression as it adjusts for multiple variables)

0.40668119528142843

### Formula for Adjusted R^2
$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$
###### n = 84 (number of observations) and p = 2 (the number of predictors)

In [10]:
x.shape

(84, 2)

In [11]:
r2 = reg.score(x,y)

n = x.shape[0]

p = x.shape[1]

adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.39203134825134023

In [12]:
# the adjusted Rsquared is significantly lower than the Rsquared:
# therefore one or more of the predictors has little to no explanatory power

In [13]:
# how do we know which predictor has little to no explanatory power? The Feature selection module!

## Feature Selection

In [14]:
# Feature selection module simplifies models - very important in machine learning
# it improves speed and prevents issues related to having too many features

# inside the module is f_regression which creates simple linear regressions of each feature and the dependant variable

In [15]:
# import f_reg from feature selection inside SKlearn
from sklearn.feature_selection import f_regression

In [16]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [17]:
# first array shows F-statistics for each of the regressions
# Second array shows the corresponding P-values

In [18]:
p_values = f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [19]:
# in output above e-11 is *10 to power of -11 OR divided by 10 to the power of 11
# e-1 *10 to the power of -1 OR divided by 10

In [20]:
p_values.round(3)

array([0.   , 0.676])

In [21]:
# first p-value is the SAT and the 2nd is the Rand 123
# Therefore we know SAT is a useful variable whereas Rand 123 is useless

### Creating a Summary Table with P-values

In [22]:
reg_summary = pd.DataFrame(data = x.columns.values, columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [23]:
reg_summary ['Coefficients'] = reg.coef_
reg_summary ['p-values'] = p_values.round(3)

In [24]:
reg_summary

Features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676

In [25]:
# P-values are one of the best ways to determine whether a variable is redundant
# We can see from here that Rand 123 is redundant