In [1]:
import numpy as np

## Declaring scalars, vectors and matrices

### Scalars

In [2]:
s = 5
s

5

In [3]:
v = np.array([5, -2,4])
v

array([ 5, -2,  4])

### Matrices

In [4]:
m = np.array([[5,12,6],[-3,0,14]])
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

### Data Types

In [5]:
type(s)      # 0D array

int

In [6]:
type(v)      # 1D array

numpy.ndarray

In [7]:
type(m)      # 2D array

numpy.ndarray

In [8]:
s_array = np.array(5)
s_array

array(5)

In [9]:
type(s_array)

numpy.ndarray

### Data Shapes

In [10]:
m.shape

(2, 3)

In [11]:
v.shape

(3,)

In [12]:
v.reshape(1,3)      # gives a row vector

array([[ 5, -2,  4]])

In [13]:
v.reshape(3,1)      # gives a column vector

array([[ 5],
       [-2],
       [ 4]])

In [14]:
s_array.shape      # just gives paranthesis as scalar is a 0D object therefore: no shape

()

## Creating a tensor

In [15]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [16]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [17]:
t = np.array([m1,m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [18]:
t.shape
# we now have a 3D object, 2 by 2 by 3

(2, 2, 3)

### Manually Creating a tensor

In [19]:
t_manual = np.array([[[5,12,6], [-3,0,14]], [[9,8,7], [1,3,-5]]])
t_manual

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

### Adding and subtracting Matrices (same as vectors)

In [26]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [27]:
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [23]:
m1 + m2

array([[14, 20, 13],
       [-2,  3,  9]])

In [24]:
m1 - m2

array([[-4,  4, -1],
       [-4, -3, 19]])

### Exceptions to matrices having the same dimentions
#### (specifically in programming)

In [28]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [29]:
m1 + 1      # each element in the matrix was increased by 1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [32]:
v1 = np.array([1,2,3,4,5])
v1

array([1, 2, 3, 4, 5])

In [33]:
v1 + 1

array([2, 3, 4, 5, 6])

## Transposing a Matrix

In [34]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [35]:
A.T     # Simply, .T will transpose any matrix

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [36]:
# Vectors (1D arrays) in Python, don't get transposed, e.g.
x = np.array([1,2,3])
x

array([1, 2, 3])

In [37]:
x.T        # yields the same result as 1D arrays cannot be transposed in Python

array([1, 2, 3])

In [38]:
x.shape

(3,)

In [41]:
x_reshaped = x.reshape(1,3)       # however, if you reshape a vector to becoming a 2D matrix, it can then be transposed
x_reshaped

array([[1, 2, 3]])

In [42]:
x_reshaped.T

array([[1],
       [2],
       [3]])

## Dot Product

In [43]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [44]:
np.dot(x,y)      # .dot gives us the dot product (multiplies each corresponding element and finds their sum)

-66

### Scalar * Vector

In [48]:
print(x)
5*x
# when we multiply a vector by a scalar, we get the same length
# the initial vector has been SCALED 5 times

[ 2  8 -4]


array([ 10,  40, -20])

### Scalar * Matrix

In [49]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [50]:
3*A

array([[15, 36, 18],
       [-9,  0, 42]])

### Matrix * Matrix

In [56]:
B = np.array([[2,-1],[8,0],[3,0]])
B

array([[ 2, -1],
       [ 8,  0],
       [ 3,  0]])

In [57]:
np.dot(A,B)

array([[124,  -5],
       [ 36,   3]])